Transform json via stack programming

diff --git a/jp b/jp
--- a/jp
+++ b/jp
@@ -6,7 +6,7 @@
 # The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 #
 # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-declare JP_TRACE JP_LINE JP_COL JP_BUF JP_C JP_IN JP_OUT JP_R JP_OBJ_COUNT
+declare JP_TRACE JP_LINE JP_COL JP_BUF JP_C JP_IN JP_OUT JP_R JP_OBJ_COUNT JP_INDENT="  " JP_PRETTY
 
 function jp.error {
   echo "Error: $1 at line $JP_LINE, column $JP_COL" >&2
@@ -288,49 +288,61 @@ function jp.parse_json {
   jp.read_next
 }
 
+function jp.type {
+  jp.trace "type:$1"
+  JP_TYPEDEC=$(declare -p "$1" 2> /dev/null)
+  if (( $? > 0 ));then
+    JP_TYPE="scalar"
+  elif [[ "$JP_TYPEDEC" == "declare --"* ]];then
+    JP_TYPE="indirect-ref"
+  elif [[ "$JP_TYPEDEC" == "declare -a"* ]];then
+    JP_TYPE="array"
+  elif [[ "$JP_TYPEDEC" == "declare -A"* ]];then
+    JP_TYPE="assoc-array"
+  elif [[ "$JP_TYPEDEC" == "declare -n"* ]];then
+    local name=${JP_TYPEDEC#*\"}
+    jp.type "${name:0:-1}"
+  else
+    JP_TYPE=
+  fi
+}
+
 function jp.to_json {
   jp.trace "to_json:$1"
-  arg="$1"
-  argtype=$(declare -p "$arg" 2> /dev/null)
-  if (( $? > 0 ));then
-    jp.trace "scalar"
-    JP_OUT+=("$arg")
-  elif [[ "$argtype" == "declare --"* ]];then
-    jp.trace "indirect-ref"
-    eval "JP_OUT+=(\$$arg)"
-  elif [[ "$argtype" == "declare -a"* ]];then
-    jp.trace "array"
-    JP_OUT+=('[')
-    local -n arr="$arg"
-    local i=0
-    local len=${#arr[@]}
-    while (( i < len  ));do
-      jp.to_json "${arr[$i]}"
-      (( i++ ))
-      (( i < len )) && JP_OUT+=(',')
-    done
-    JP_OUT+=(']')
-  elif [[ "$argtype" == "declare -A"* ]];then
-    jp.trace "assoc-array"
-    JP_OUT+=('{')
-    local -n aar="$arg"
-    local i=0
-    local len=${#aar[@]}
-    for k in "${!aar[@]}";do
-      jp.to_json "$k"
-      JP_OUT+=(':')
-      jp.to_json "${aar[$k]}"
-      (( i++ ))
-      (( i < len )) && JP_OUT+=(',')
-    done
-    JP_OUT+=('}')
-  elif [[ "$argtype" == "declare -n"* ]];then
-    jp.trace "nameref"
-    local name=${argtype#*\"}
-    jp.to_json ${name:0:-1}
-  else
-    jp.error "unknown type $argtype" || return
-  fi
+  jp.type "$1"
+  jp.trace "$JP_TYPE"
+  local arg="$1"
+  case "$JP_TYPE" in
+    'scalar') JP_OUT+=("$arg");;
+    'indirect-ref') eval "JP_OUT+=(\$$arg)";;
+    'array')
+      JP_OUT+=('[')
+      local -n arr="$arg"
+      local i=0
+      local len=${#arr[@]}
+      while (( i < len  ));do
+        jp.to_json "${arr[$i]}"
+        (( i++ ))
+        (( i < len )) && JP_OUT+=(',')
+      done
+      JP_OUT+=(']')
+      ;;
+    'assoc-array')
+      JP_OUT+=('{')
+      local -n aar="$arg"
+      local i=0
+      local len=${#aar[@]}
+      for k in "${!aar[@]}";do
+        jp.to_json "$k"
+        JP_OUT+=(':')
+        jp.to_json "${aar[$k]}"
+        (( i++ ))
+        (( i < len )) && JP_OUT+=(',')
+      done
+      JP_OUT+=('}')
+      ;;
+    *) jp.error "unknown type" || return
+  esac
 }
 
 function jp.slurp_input {
@@ -407,31 +419,166 @@ function jp.uglyprint {
   echo
 }
 
+function jp.pop {
+  (( JP_STACKSIZE-- ))
+  JP_R="${JP_STACK[$JP_STACKSIZE]}"
+  JP_STACK[$JP_STACKSIZE]=
+}
+
+function jp.push {
+  jp.trace "push"
+  JP_STACK[$JP_STACKSIZE]="$1"
+  (( JP_STACKSIZE++ ))
+  return 0
+}
+
+function jp.swap {
+  jp.pop
+  local temp="$JP_R"
+  jp.pop
+  jp.push "$temp"
+  jp.push "$JP_R"
+}
+
+function jp.merge {
+  jp.trace "merge"
+  jp.pop
+  local left="$JP_R"
+  jp.type "$left"
+  local lefttype="$JP_TYPE"
+
+  local count="$JP_STACKSIZE"
+  while [[ $count > 0 ]];do
+  echo "count is $count"
+  jp.pop
+  case "$lefttype" in
+    'scalar')
+      jp.type "$JP_R"
+      case "$JP_TYPE" in
+        'scalar')
+          jp.error "cannot merge two scalars" || return
+          ;;
+        'array')
+          eval $left='("$left" "${'"$JP_R"'[@]}")'
+          ;;
+        'assoc-array')
+          jp.error "cannot merge a scalar into an object" || return
+          ;;
+        *) jp.error "unrecognized type: '$JP_TYPE'" || return
+      esac
+      ;;
+    'array')
+      jp.type "$JP_R"
+      case "$JP_TYPE" in
+        'scalar')
+          eval $left+='("$JP_R")'
+          ;;
+        'array')
+          eval $left+='("${'"$JP_R"'[@]}")'
+          ;;
+        'assoc-array')
+          eval $left+='("$JP_R")'
+          ;;
+        *) jp.error "unrecognized type: '$JP_TYPE'" || return
+      esac
+      ;;
+    'assoc-array')
+      jp.type "$JP_R"
+      case "$JP_TYPE" in
+        'scalar')
+          jp.error "cannot merge a scalar into an object" || return
+          ;;
+        'array')
+          jp.error "cannot merge an array into into an object" || return
+          ;;
+        'assoc-array')
+          local -n right=$JP_R
+          for k in "${!right[@]}";do
+            eval $left['"$k"']='"${right[$k]}"'
+          done
+          ;;
+        *) jp.error "unrecognized type: '$JP_TYPE'" || return
+      esac
+      ;;
+    *) jp.error "unrecognized type: '$JP_TYPE'" || return
+  esac
+  (( count-- ))
+  done
+  jp.push $left
+}
+
+function jp.keys {
+  jp.pop
+  jp.type "$JP_R"
+  if [[ "$JP_TYPE" == 'assoc-array' ]];then
+    local -n left=$JP_R
+    for k in "${!left[@]}";do
+      jp.push "$k"
+    done
+  else
+    jp.error "keys only works on objects, I saw a: '$JP_TYPE'" || return
+  fi
+}
+
+function jp.values {
+  jp.pop
+  jp.type "$JP_R"
+  if [[ "$JP_TYPE" == 'assoc-array' ]];then
+    local -n left=$JP_R
+    for k in "${!left[@]}";do
+      jp.push "${left[$k]}"
+    done
+  else
+    jp.error "values only works on objects, I saw a: '$JP_TYPE'" || return
+  fi
+}
+
 function jp.run {
   jp.trace "run"
-  local pretty=$1 before="$2" after="$3" indent="$4"
   JP_OBJ_COUNT=0
-  eval "$before"
   jp.parse_json "$JP_IN" || return
-  eval "$after"
-  jp.to_json "$JP_R"
-  if [[ $pretty ]];then
-    jp.prettyprint "$indent"
-  else
-    jp.uglyprint
-  fi
-  JP_OUT=()
+  jp.push "$JP_R"
+  for arg in "$@";do
+    jp.parse_json "$arg" 2>/dev/null
+    if [[ $? > 0 ]];then
+      JP_C=
+      JP_BUF=
+      eval "$arg"
+      if [[ $? > 0 ]];then
+        jp.error "filter failed to process '$arg'"
+        return
+      fi
+    else
+      jp.push "$JP_R"
+    fi
+  done
+  while [[ $JP_STACKSIZE > 0 ]];do
+    jp.pop
+    jp.to_json "$JP_R"
+    if [[ $JP_PRETTY ]];then
+      jp.prettyprint "$JP_INDENT"
+    else
+      jp.uglyprint
+    fi
+    JP_OUT=()
+  done
 }
 
 function jp.main {
   jp.trace "main"
-  local p b a t i="  "
-  [[ -t 1 ]] && p=1 # default to pretty for a tty
-  eval "$1"
-  [[ $t ]] && JP_TRACE=1
+  [[ -t 1 ]] && JP_PRETTY=1 # default to pretty for a tty
+  while getopts ":pPti:" opt; do
+    case "$opt" in
+      'p') JP_PRETTY=1;;
+      'P') JP_PRETTY=;;
+      't') JP_TRACE=1;;
+      'i') JP_INDENT="$OPTARG";;
+    esac
+    shift $((OPTIND-1))
+  done
   jp.slurp_input
   while :;do
-    jp.run "$p" "$b" "$a" "$i" || return
+    jp.run "$@" || return
     jp.drop_blanks
     if [[ "$JP_C" ]];then
       jp.expect $'\n' || return
